# -*- coding: utf-8 -*-
"""IK_RAG_Workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0GGJZ34KNhAKOmrE41upTfoj_sCjnN0
"""

from google.colab import userdata

# Retrieve the API key from Colab Secrets, assuming it's stored under the name 'OPENAI_API_KEY'
OPENAI_APIKEY = userdata.get('OPENAI_API_KEY')

import json
import numpy as np
from openai import OpenAI
from sklearn.metrics.pairwise import cosine_similarity

# Initialize OpenAI client (it automatically picks up the os.environ key we set earlier)
client = OpenAI(api_key=OPENAI_APIKEY)
embedding_model = 'text-embedding-3-small'

# Load the synthetic tickets data
# Since we are inside the repository folder, the path is adjusted to find the data
with open('data/synthetic_tickets.json', 'r') as f:
    tickets = json.load(f)

# Combine title and description for a richer embedding context
texts = [f"{t['title']}. {t['description']}" for t in tickets]

print("Generating embeddings for all tickets... (this might take a few seconds)")
response = client.embeddings.create(input=texts, model=embedding_model)
embeddings = np.array([data.embedding for data in response.data])
print(f"✓ Successfully generated {len(embeddings)} embeddings.\n")

# --- EXERCISE 1 START ---
# Task: Modify the search query here!
query = "Database is running very slowly"

print(f"Searching for: '{query}'")
# Embed the query
q_response = client.embeddings.create(input=[query], model=embedding_model)
q_emb = np.array([q_response.data[0].embedding])

# Calculate cosine similarity between the query and all ticket embeddings
similarities = cosine_similarity(q_emb, embeddings)[0]

# Get top 5 results
top_k = 5
top_indices = np.argsort(similarities)[::-1][:top_k]

print("\nTop Results:")
for rank, idx in enumerate(top_indices, 1):
    ticket = tickets[idx]
    score = similarities[idx]
    print(f"\n#{rank} - Similarity Score: {score:.4f}")
    print(f"Ticket ID: {ticket['ticket_id']} | Category: {ticket['category']}")
    print(f"Title: {ticket['title']}")
    print(f"Description: {ticket['description']}")



# --- EXERCISE 2 & 3 COMBINED ---
# 1. We change top_k to 10 to fetch more results
top_k = 10
top_indices = np.argsort(similarities)[::-1][:top_k]

# Test 1: Let's run our relevant query with a threshold
print("="*50)
print(f"SEARCH WITH THRESHOLD (Query: '{query}')")
print("="*50)

visible_results = 0
for rank, idx in enumerate(top_indices, 1):
    ticket = tickets[idx]
    score = similarities[idx]

    # EXERCISE 3 LINE: Skip results below a 0.5 similarity score
    if score < 0.5:
        continue

    visible_results += 1
    print(f"\n#{rank} - Similarity Score: {score:.4f}")
    print(f"Ticket ID: {ticket['ticket_id']} | Category: {ticket['category']}")
    print(f"Title: {ticket['title']}")

print(f"\n✓ Done. Showed {visible_results} out of {top_k} results based on threshold.")

# --- EXERCISE 4: COMPARE TWO QUERIES (RUN AFTER DEMO PART 5) ---

# Compare two queries as requested by Exercise 4
query1 = "Login authentication failed"
query2 = "Slow database performance"

print("\n" + "="*80)
print("COMPARING TWO QUERIES")
print("="*80)

for q in [query1, query2]:
    # 1. Generate embedding for the individual query
    response = client.embeddings.create(input=[q], model=embedding_model)
    q_emb = np.array([response.data[0].embedding])

    # 2. Calculate similarities against the existing embeddings matrix
    sims = cosine_similarity(q_emb, embeddings)[0]

    # 3. Find the best match index
    top_idx = np.argmax(sims)

    # 4. Print results matching the exercise format
    print(f"\nQuery: '{q}'")
    print(f"  Best match: {tickets[top_idx]['title']}")
    print(f"  Score: {sims[top_idx]:.4f}")



# --- EXERCISE 5: SEMANTIC UNDERSTANDING ---
import numpy as np
from openai import OpenAI
from sklearn.metrics.pairwise import cosine_similarity

client = OpenAI(api_key=OPENAI_APIKEY)
model = 'text-embedding-3-small'

# These mean the SAME thing but use DIFFERENT words (except the last one which is a different topic)
texts = [
    "User authentication failed",      # Sentence 0
    "Login credentials rejected",       # Sentence 1
    "Cannot sign in to account",        # Sentence 2
    "Database connection timeout",      # Sentence 3
]

print("Generating embeddings for semantic comparison...")
response = client.embeddings.create(input=texts, model=model)
embeddings = np.array([data.embedding for data in response.data])

# Calculate all pairwise similarities
similarity_matrix = cosine_similarity(embeddings)

print("\nSimilarity Matrix Results:")
print("-" * 60)
for i, text1 in enumerate(texts):
    for j, text2 in enumerate(texts):
        if i < j:  # Only print upper triangle so we don't repeat comparisons
            sim = similarity_matrix[i][j]
            print(f"Score: {sim:.3f}  |  '{text1}' vs '{text2}'")



# --- EXERCISE 7: BATCH VS SINGLE EMBEDDING ---
import time
from openai import OpenAI

# Client initialized directly with your key
client = OpenAI(api_key=OPENAI_APIKEY)
model = 'text-embedding-3-small'

texts = [
    "Password reset not working",
    "Database connection timeout",
    "App crashes on startup",
    "Payment declined error",
    "Email notifications delayed",
]

# Method 1: SLOW - One API call per text
print("Method 1: Running single API calls sequentially...")
start = time.time()
for text in texts:
    response = client.embeddings.create(input=[text], model=model)
time_slow = time.time() - start
print(f"  → Single Calls Time: {time_slow:.2f} seconds")

# Method 2: FAST - One single API call for all texts combined
print("\nMethod 2: Running batch API call...")
start = time.time()
response = client.embeddings.create(input=texts, model=model)
time_fast = time.time() - start
print(f"  → Batch Call Time: {time_fast:.2f} seconds")

# Compare the speeds
speed_difference = time_slow / time_fast if time_fast > 0 else 0
print(f"\n✓ Batch is {speed_difference:.1f}x faster!")
print("💡 Rule of thumb: Always batch your embeddings in production pipelines!")



# Commented out IPython magic to ensure Python compatibility.
import os

# Check if we are already in the directory, if not, change to it
if not os.getcwd().endswith('SupportDesk-RAG-Workshop'):
#     %cd /content/SupportDesk-RAG-Workshop

print(f"Current Working Directory: {os.getcwd()}")

# --- HOUR 2: EXERCISE 6 & 7 (VECTOR STORE & FILTERING) ---
import json
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_core.documents import Document

# 1. Initialize OpenAI Embeddings with your key
embeddings_model = OpenAIEmbeddings(
    model='text-embedding-3-small',
    openai_api_key=OPENAI_APIKEY
)

# 2. Load and create documents with metadata attached
with open('data/synthetic_tickets.json', 'r') as f:
    tickets = json.load(f)

documents = []
for ticket in tickets:
    doc = Document(
        page_content=f"Title: {ticket['title']}. Description: {ticket['description']}",
        metadata={
            'ticket_id': ticket['ticket_id'],
            'category': ticket['category'],
            'priority': ticket['priority']
        }
    )
    documents.append(doc)

# 3. Create the Chroma Vector Store directly in Colab's RAM
print("Embedding documents and building Chroma Vector Database...")
chroma_store = Chroma.from_documents(
    documents,
    embeddings_model,
    collection_name="colab_exercise_store"
)
print("✓ Chroma DB is populated and ready!\n")

# --- EXERCISE 6 & 7 TASK: Search with combined metadata filters ---
query = "system not working"

# We use an $and logical filter to look ONLY for 'Authentication' tickets that are 'High' priority
combined_filter = {
    "$and": [
        {"category": "Authentication"},
        {"priority": "High"}
    ]
}

print(f"Running query: '{query}'")
print("Applying structural filter: Category == 'Authentication' AND Priority == 'High'\n")

# Run search returning BOTH the matching document and its calculated Distance score
results_with_scores = chroma_store.similarity_search_with_score(query, k=3, filter=combined_filter)

print(f"Results Found ({len(results_with_scores)}):")
print("-" * 60)
for i, (doc, score) in enumerate(results_with_scores, 1):
    print(f"#{i} - L2 Distance Score: {score:.4f}")
    print(f"    Ticket ID: {doc.metadata['ticket_id']}")
    print(f"    Priority:  [{doc.metadata['priority']}]")
    print(f"    Category:  [{doc.metadata['category']}]")
    print(f"    Content:   {doc.page_content[:100]}...")
    print()



# --- HOUR 3: EXERCISE 5 & 8 (COMPARE & BENCHMARK INDEXES) ---
import json
import time
import os
from llama_index.core import VectorStoreIndex, KeywordTableIndex, Document, Settings
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.llms.openai import OpenAI

# 1. Configure global LlamaIndex settings with your credentials
Settings.embed_model = OpenAIEmbedding(
    model='text-embedding-3-small',
    api_key=OPENAI_APIKEY
)
Settings.llm = OpenAI(
    model='gpt-4o-mini',
    api_key=OPENAI_APIKEY
)

# 2. Load the synthetic data
with open('data/synthetic_tickets.json', 'r', encoding='utf-8') as f:
    tickets = json.load(f)

# Convert raw data into LlamaIndex Document nodes
documents = []
for t in tickets:
    doc = Document(
        text=f"Title: {t['title']}\nDescription: {t['description']}\nResolution: {t['resolution']}",
        metadata={'ticket_id': t['ticket_id'], 'category': t['category']}
    )
    documents.append(doc)

print("Building indexes for documents...\n")

# --- BENCHMARK 1: Vector Store Index (Semantic Search) ---
start = time.time()
vector_index = VectorStoreIndex.from_documents(documents)
vector_time = time.time() - start
print(f"-> Vector Index build time: {vector_time:.2f} seconds")

# --- BENCHMARK 2: Keyword Table Index (Exact Matching) ---
start = time.time()
keyword_index = KeywordTableIndex.from_documents(documents)
keyword_time = time.time() - start
print(f"-> Keyword Index build time: {keyword_time:.2f} seconds\n")

# --- COMPARING QUERIES SIDE-BY-SIDE ---
# Test 1: Conceptual Query
query_semantic = "authentication login problem"
print("=" * 60)
print(f"QUERY: '{query_semantic}'")
print("=" * 60)

vec_engine = vector_index.as_query_engine(similarity_top_k=1)
vec_response = vec_engine.query(query_semantic)
print(f"Vector Index Result:\n  {str(vec_response).strip()}\n")

# Test 2: Exact Ticket ID Query
query_exact = "TICK-005"
print("=" * 60)
print(f"QUERY: '{query_exact}'")
print("=" * 60)

kw_engine = keyword_index.as_query_engine()
kw_response = kw_engine.query(query_exact)
print(f"Keyword Index Result:\n  {str(kw_response).strip()}")



